<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CS0-46" ignored="0" name="Default test" tests="10" failures="2" timestamp="20 Apr 2018 13:57:47 GMT" time="10.87" errors="0">
  <testcase name="invalidDataTests" time="0.517" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="invalidDataTests" time="0.326" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="invalidDataTests" time="0.32" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="invalidDataTests" time="0.297" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="validDataTests" time="0.313" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="validDataTests" time="0.31" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="validDataTests" time="0.337" classname="cs265b.CS265B_Selenium_Week10">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;SCALENE&amp;gt; but was:&amp;lt;GREATER THAN 180&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<SCALENE> but was:<GREATER THAN 180>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)at cs265b.CS265B_Selenium_Week10.CS265BLab7_TestTemplate(CS265B_Selenium_Week10.java:131)at cs265b.CS265B_Selenium_Week10.validDataTests(CS265B_Selenium_Week10.java:142)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- validDataTests -->
  <testcase name="validDataTests" time="0.329" classname="cs265b.CS265B_Selenium_Week10">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;SCALENE&amp;gt; but was:&amp;lt;GREATER THAN 180&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<SCALENE> but was:<GREATER THAN 180>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)at cs265b.CS265B_Selenium_Week10.CS265BLab7_TestTemplate(CS265B_Selenium_Week10.java:131)at cs265b.CS265B_Selenium_Week10.validDataTests(CS265B_Selenium_Week10.java:142)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- validDataTests -->
  <testcase name="validDataTests" time="0.328" classname="cs265b.CS265B_Selenium_Week10"/>
  <testcase name="validDataTests" time="0.313" classname="cs265b.CS265B_Selenium_Week10"/>
</testsuite> <!-- Default test -->
